package com.project.back_end.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotNull;

@Entity
public class Admin {

    // 1. 'id' field:
    // - Represents the unique identifier for the Admin entity.
    // - Auto-generated by the database.
    // - Primary key of the entity.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // 2. 'username' field:
    // - Represents the username of the admin.
    // - Used to log into the system.
    // - Cannot be null.
    @NotNull(message = "Username cannot be null")
    private String username;

    // 3. 'password' field:
    // - Represents the password of the admin.
    // - WRITE_ONLY prevents the password from appearing in JSON responses.
    // - Cannot be null.
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    @NotNull(message = "Password cannot be null")
    private String password;

    // 4. No-argument constructor required by JPA.
    public Admin() {
    }

    // Parameterized constructor.
    public Admin(String username, String password) {
        this.username = username;
        this.password = password;
    }

    // 5. Getters and Setters.

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}
