package com.project.back_end.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

import java.util.ArrayList;
import java.util.List;

@Entity
public class Doctor {

    // 1. Unique identifier and primary key.
    //    The ID is automatically generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // 2. Doctor's name.
    //    Required and must contain between 3 and 100 characters.
    @NotNull(message = "Doctor name cannot be null")
    @Size(
        min = 3,
        max = 100,
        message = "Doctor name must be between 3 and 100 characters"
    )
    private String name;

    // 3. Doctor's medical specialty.
    //    Required and must contain between 3 and 50 characters.
    @NotNull(message = "Specialty cannot be null")
    @Size(
        min = 3,
        max = 50,
        message = "Specialty must be between 3 and 50 characters"
    )
    private String specialty;

    // 4. Doctor's email address.
    //    Required and must use a valid email format.
    @NotNull(message = "Email cannot be null")
    @Email(message = "Email must be valid")
    private String email;

    // 5. Doctor's password.
    //    Required and must contain at least 6 characters.
    //    WRITE_ONLY prevents the password from appearing in JSON responses.
    @NotNull(message = "Password cannot be null")
    @Size(
        min = 6,
        message = "Password must be at least 6 characters long"
    )
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String password;

    // 6. Doctor's phone number.
    //    Required and must contain exactly 10 digits.
    @NotNull(message = "Phone number cannot be null")
    @Pattern(
        regexp = "^[0-9]{10}$",
        message = "Phone number must contain exactly 10 digits"
    )
    private String phone;

    // 7. Doctor's available appointment time slots.
    //    Stored as a separate collection in the database.
    @ElementCollection
    private List<String> availableTimes = new ArrayList<>();

    // No-argument constructor required by JPA.
    public Doctor() {
    }

    // Parameterized constructor.
    public Doctor(
            String name,
            String specialty,
            String email,
            String password,
            String phone,
            List<String> availableTimes
    ) {
        this.name = name;
        this.specialty = specialty;
        this.email = email;
        this.password = password;
        this.phone = phone;
        this.availableTimes = availableTimes;
    }

    // 8. Getters and setters.

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSpecialty() {
        return specialty;
    }

    public void setSpecialty(String specialty) {
        this.specialty = specialty;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public List<String> getAvailableTimes() {
        return availableTimes;
    }

    public void setAvailableTimes(List<String> availableTimes) {
        this.availableTimes = availableTimes;
    }
}